algolia:
  application_id: null
  index_name: null
  powered_by: null
  search_only_api_key: null
analytics:
  plausible:
    domain: ouaisfieu.github.io/mm
  # provider: plausible
atom_feed:
  hide: null
  path: null
author:
  avatar: /assets/images/avatar.jpg
  bio: Collectif citoyen pour une web-démocratie accessible
  links:
  - icon: fab fa-fw fa-github
    label: GitHub
    url: https://github.com/ouaisfieu
  - icon: fas fa-fw fa-globe
    label: Site
    url: https://ouaisfieu.github.io
  location: Bruxelles
  name: ouaisfi·eu
baidu_site_verification: null
baseurl: /mm
bing_site_verification: null
breadcrumbs: true
category_archive:
  path: /categories/
  type: liquid
comments:
  discourse:
    server: null
  disqus:
    shortname: null
  facebook:
    appid: null
    colorscheme: null
    num_posts: null
  giscus:
    category_id: null
    category_name: null
    discussion_term: null
    emit_metadata: null
    input_position: null
    lang: null
    lazy: null
    reactions_enabled: null
    repo_id: null
    strict: null
    theme: null
  provider: null
  staticman:
    branch: null
    endpoint: null
  utterances:
    issue_term: null
    theme: null
compress_html:
  clippings: all
  ignore:
    envs: development
copyright: null
copyright_url: null
defaults:
- scope:
    path: ''
    type: posts
  values:
    author_profile: true
    comments: null
    layout: single
    read_time: true
    related: true
    share: true
description: Un site construit avec Jekyll + Minimal Mistakes
enable_copy_code_button: null
encoding: utf-8
excerpt_separator: '


  '
exclude:
- '*.sublime-project'
- '*.sublime-workspace'
- vendor
- .asset-cache
- .bundle
- .jekyll-assets-cache
- .sass-cache
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- minimal-mistakes-jekyll.gemspec
- node_modules
- package.json
- package-lock.json
- Rakefile
- README
- tmp
- /docs
- /test
facebook:
  app_id: null
  publisher: null
  username: null
footer:
  links:
  - icon: fab fa-fw fa-twitter-square
    label: Twitter
  - icon: fab fa-fw fa-facebook-square
    label: Facebook
  - icon: fab fa-fw fa-github
    label: GitHub
  - icon: fab fa-fw fa-gitlab
    label: GitLab
  - icon: fab fa-fw fa-bitbucket
    label: Bitbucket
  - icon: fab fa-fw fa-instagram
    label: Instagram
  since: '2013'
google:
  instant_search: null
  search_engine_id: null
google_site_verification: null
highlighter: rouge
include:
- .htaccess
- _pages
incremental: false
keep_files:
- .git
- .svn
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  hard_wrap: false
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
locale: en-US
logo: null
lsi: false
lunr:
  search_within_pages: null
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
masthead_title: null
minimal_mistakes_skin: mint
name: Your Name
naver_site_verification: null
og_image: /assets/images/og.jpg
paginate: 5
paginate_path: /page:num/
pagination:
  category: posts
  collection: posts
  debug: false
  limit: 0
  locale: ''
  per_page: 10
  permalink: /page/:num/
  sort_field: date
  sort_reverse: true
  tag: ''
  title: :title - page :num
  trail:
    after: 2
    before: 2
permalink: /:categories/:title/
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-include-cache
reCaptcha:
  secret: null
  siteKey: null
remote_theme: mmistakes/minimal-mistakes@4.27.1
repository: ouaisfieu/mm
rtl: null
sass:
  sass_dir: _sass
  style: compressed
search: true
search_full_content: true
search_provider: null
social:
  links: null
  name: null
  type: null
subtitle: Rendre l’information accessible à tous
tag_archive:
  path: /tags/
  type: liquid
teaser: null
timezone: null
title: Découvrabilité & Citoyenneté
title_separator: '-'
twitter:
  username: ouaisfieu
url: https://ouaisfieu.github.io
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-include-cache
words_per_minute: 200
yandex_site_verification: null
